port = 8085
host = "0.0.0.0"
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
tokens = ["duckduckgo-chat-api-token"]
ddg_chat_api_url = "https://duckduckgo.com/"

[model_mapping]
"ddg/gpt-4o-mini" = "gpt-4o-mini"
"ddg/claude-3-haiku" = "claude-3-haiku-20240307"
"ddg/mixtral-8x7b" = "mistralai/Mixtral-8x7B-Instruct-v0.1"
"ddg/meta-Llama-3-1-70B-Instruct-Turbo" = "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"

